name: build mmaps

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build mmaps
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy SSH key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.MMAPS_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com
      - name: Checkout stm32-rs
        uses: actions/checkout@v2
        with:
          path: stm32-rs
      - name: Checkout mmaps
        uses: actions/checkout@v2
        with:
          repository: stm32-rs/stm32-rs-mmaps
          ssh-key: ~/.ssh/id_rsa
          path: stm32-rs-mmaps
      - name: Install Python dependencies
        run: |
          pip3 install --user setuptools wheel
          pip3 install --user svdtools
      - name: Put pip binary directory into path
        run: |
          echo "::add-path::~/.local/bin"
      - name: Build and publish
        run: |
          cd stm32-rs
          COMMIT=$(git rev-parse HEAD)
          make -j2 mmaps
          mv mmaps/* ../stm32-rs-mmaps/
          cd ../stm32-rs-mmaps
          git config user.name "stm32-rs builder"
          git config user.email "action@github.com"
          git add .
          git commit -m "stm32-rs master $COMMIT"
          git push origin master
